version: '3'
services:
    web:
        image: nginx:1.13
        environment:
            VIRTUAL_HOST: 'akbarratt.com,origin.akbarratt.com,www.akbarratt.com'
            LETSENCRYPT_HOST: 'akbarratt.com,origin.akbarratt.com,www.akbarratt.com'
        volumes:
          - ./web:/usr/share/nginx/html 
